# Generated by Django 3.2.5 on 2021-07-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_id',
            new_name='contact',
        ),
    ]
